/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.UPAO.proyecto.app;

import javax.swing.ImageIcon;

/**
 *
 * @author Asus
 */
public class LOCALES extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LOCALES.class.getName());

    /**
     * Creates new form LOCALES
     */
    public LOCALES() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Frase = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        RotacionProductos = new javax.swing.JButton();
        LogoRentabilidad = new javax.swing.JLabel();
        RankingFinanciero = new javax.swing.JButton();
        LogoRanking = new javax.swing.JLabel();
        Rotacionlogo = new javax.swing.JLabel();
        Rentabilidad = new javax.swing.JButton();
        FondoKuyay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Frase.setFont(new java.awt.Font("Harlow Solid Italic", 0, 12)); // NOI18N
        Frase.setForeground(new java.awt.Color(255, 0, 0));
        Frase.setText("Todo lo que necesitas, al alcance");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Frase, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 787, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addComponent(Frase))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, -1));

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOCALES");
        jPanel2.add(jLabel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1130, 80));

        RotacionProductos.setText("ROTACIONPRODUCTOS");
        RotacionProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotacionProductosActionPerformed(evt);
            }
        });
        getContentPane().add(RotacionProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 160, -1));

        LogoRentabilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/imagenes/1260410-convertido-a-170x130.jpeg"))); // NOI18N
        LogoRentabilidad.setText("jLabel1");
        getContentPane().add(LogoRentabilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 170, 150));

        RankingFinanciero.setText("RANKING FINANCIERO");
        RankingFinanciero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RankingFinancieroActionPerformed(evt);
            }
        });
        getContentPane().add(RankingFinanciero, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, 170, -1));

        LogoRanking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/imagenes/Captura de pantalla 2025-10-07 212856-convertido-a-170x140.jpeg"))); // NOI18N
        getContentPane().add(LogoRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 170, 130));

        Rotacionlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/imagenes/Captura de pantalla 2025-10-07 210007-convertido-a-160x130.jpeg"))); // NOI18N
        getContentPane().add(Rotacionlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 160, 130));

        Rentabilidad.setText("RENTABILIDAD");
        Rentabilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentabilidadActionPerformed(evt);
            }
        });
        getContentPane().add(Rentabilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 170, -1));

        FondoKuyay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/imagenes/IconoKuyayLocal-convertido-a-1130x440.jpeg"))); // NOI18N
        getContentPane().add(FondoKuyay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1130, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RotacionProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RotacionProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RotacionProductosActionPerformed

    private void RentabilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentabilidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RentabilidadActionPerformed

    private void RankingFinancieroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RankingFinancieroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RankingFinancieroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LOCALES().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoKuyay;
    private javax.swing.JLabel Frase;
    private javax.swing.JLabel LogoRanking;
    private javax.swing.JLabel LogoRentabilidad;
    private javax.swing.JButton RankingFinanciero;
    private javax.swing.JButton Rentabilidad;
    private javax.swing.JButton RotacionProductos;
    private javax.swing.JLabel Rotacionlogo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
