/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.UPAO.proyecto.app;

import edu.UPAO.proyecto.LoginController;
import javax.swing.JOptionPane;

/**
 *
 * @author WIN-10
 */
public class LoginjFrame extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LoginjFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Right = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Left = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_identificacion = new javax.swing.JTextField();
        tf_contraseña = new javax.swing.JPasswordField();
        btn_ingresar = new javax.swing.JButton();
        btn_olivdeContraseña = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        Right.setBackground(new java.awt.Color(255, 255, 255));
        Right.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel5.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("SISTEMA DE VENTAS KUYAY");

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jLabel5)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jPanel1.add(Right);
        Right.setBounds(0, 0, 400, 500);

        Left.setBackground(new java.awt.Color(255, 153, 0));
        Left.setMinimumSize(new java.awt.Dimension(400, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("INICIO DE SESION");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("IDENTIFICACION");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CONTRASEÑA:");

        tf_identificacion.setBackground(new java.awt.Color(255, 255, 255));
        tf_identificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_identificacionActionPerformed(evt);
            }
        });

        tf_contraseña.setBackground(new java.awt.Color(255, 255, 255));
        tf_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_contraseñaActionPerformed(evt);
            }
        });

        btn_ingresar.setBackground(new java.awt.Color(0, 153, 153));
        btn_ingresar.setForeground(new java.awt.Color(255, 255, 255));
        btn_ingresar.setText("INGRESAR");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });

        btn_olivdeContraseña.setBackground(new java.awt.Color(255, 153, 0));
        btn_olivdeContraseña.setForeground(new java.awt.Color(204, 0, 0));
        btn_olivdeContraseña.setText("Olvide mi contraseña");
        btn_olivdeContraseña.setBorderPainted(false);
        btn_olivdeContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_olivdeContraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_olivdeContraseña)
                            .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                                    .addComponent(tf_contraseña))
                                .addComponent(tf_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2))
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btn_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_olivdeContraseña)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jPanel1.add(Left);
        Left.setBounds(400, 0, 400, 502);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_contraseñaActionPerformed
        realizarLogin();
    }//GEN-LAST:event_tf_contraseñaActionPerformed

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        realizarLogin();
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_olivdeContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_olivdeContraseñaActionPerformed
        JOptionPane.showMessageDialog(this,
                "Contacte al administrador del sistema para recuperar su contraseña.\n"
                + "Teléfono: 123-456-789\n"
                + "Email: soporte@kuyay.com",
                "Recuperar Contraseña",
                JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btn_olivdeContraseñaActionPerformed

    private void tf_identificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_identificacionActionPerformed
        // Al presionar Enter en identificación, pasar a contraseña
        tf_contraseña.requestFocus();
    }//GEN-LAST:event_tf_identificacionActionPerformed

    private void realizarLogin() {
        String identificacion = tf_identificacion.getText().trim();
        String password = new String(tf_contraseña.getPassword());

        if (identificacion.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, complete todos los campos",
                    "Campos Incompletos",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (LoginController.validarCredenciales(identificacion, password)) {
            // ✅ OBTENER TIPO DE USUARIO
            String tipoUsuario = LoginController.getTipoUsuario(identificacion);
            String mensajeBienvenida = "";

            // ✅ REDIRIGIR SEGÚN EL TIPO DE USUARIO
            if ("gerente".equals(tipoUsuario)) {
                mensajeBienvenida = "¡Bienvenido Gerente!";
                JOptionPane.showMessageDialog(this,
                        mensajeBienvenida,
                        "Login Exitoso",
                        JOptionPane.INFORMATION_MESSAGE);

                // Abrir Panel_Gerente
                Panel_Gerente panelGerente = new Panel_Gerente();
                panelGerente.setVisible(true);

            } else if ("admin".equals(tipoUsuario)) {
                mensajeBienvenida = "¡Bienvenido Administrador!";
                JOptionPane.showMessageDialog(this,
                        mensajeBienvenida,
                        "Login Exitoso",
                        JOptionPane.INFORMATION_MESSAGE);

                // ✅ Abrir el AdministradorPanel
                AdministradorPanel adminPanel = new AdministradorPanel();
                adminPanel.setLocationRelativeTo(null); // Centrar en pantalla
                adminPanel.setVisible(true);

            } else {
                // Cajeros y otros usuarios van al Menu2 normal
                mensajeBienvenida = "¡Bienvenido al Sistema Kuyay!";
                JOptionPane.showMessageDialog(this,
                        mensajeBienvenida,
                        "Login Exitoso",
                        JOptionPane.INFORMATION_MESSAGE);

                Menu2 menuPrincipal = new Menu2();
                menuPrincipal.setVisible(true);
            }

            // Cerrar login
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Identificación o contraseña incorrectos",
                    "Error de Login",
                    JOptionPane.ERROR_MESSAGE);

            tf_contraseña.setText("");
            tf_identificacion.requestFocus();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginjFrame().setVisible(true);
            }
        });
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Right;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_olivdeContraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField tf_contraseña;
    private javax.swing.JTextField tf_identificacion;
    // End of variables declaration//GEN-END:variables
}
