/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.UPAO.proyecto.app;

import edu.UPAO.proyecto.DAO.ProductoDAO;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import edu.UPAO.proyecto.ProductoController;
import edu.UPAO.proyecto.PromocionController;
import edu.UPAO.proyecto.Modelo.Producto;
import java.io.File;
import javax.swing.SpinnerNumberModel;

public class Menu2 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu2.class.getName());

    /**
     * Creates new form Menu2
     */
    public Menu2() {

        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        inicializarTablaProductos(); // ✅ Esto asegura el orden correcto
        cargarProductosEnTabla();
        txtObservaciones.setEnabled(false);
        txtCupon.setEnabled(false);

        spCantidad.setModel(new SpinnerNumberModel(1, 1, Integer.MAX_VALUE, 1));

        SpinnerNumberModel spinnerModel = new SpinnerNumberModel(1, 1, Integer.MAX_VALUE, 1);
        sp_item.setModel(spinnerModel);

        spCantidad.setModel(new SpinnerNumberModel(1, 1, Integer.MAX_VALUE, 1));
        sp_item.setModel(new SpinnerNumberModel(1, 1, Integer.MAX_VALUE, 1));
     
        
        ///////////////////////ACA SOLO PARA LA RUEDITA/////////////////////////
        sp_item.addMouseWheelListener(e -> {
            int rot = e.getWheelRotation();
            int val = (int) sp_item.getValue();
            if (rot < 0) {
                sp_item.setValue(Math.max(1, val + 1));
            } else if (rot > 0) {
                sp_item.setValue(Math.max(1, val - 1));
            }
        });

        tablaProductos.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                spCantidad.setValue(1); // 👈 Reinicia cantidad
            }
        });

        // Al inicializar tu formulario
        spCantidad.addMouseWheelListener(e -> {
            int notches = e.getWheelRotation(); // movimiento de la rueda
            int valorActual = (int) spCantidad.getValue();

            // ✅ Recuperar la fila seleccionada en la tabla de productos
            int fila = tablaProductos.getSelectedRow();
            if (fila == -1) {
                return; // no hay producto seleccionado
            }
            DefaultTableModel modeloProductos = (DefaultTableModel) tablaProductos.getModel();
            String codigo = modeloProductos.getValueAt(fila, 0).toString();

            ProductoDAO productoDAO = new ProductoDAO();
            Producto producto = productoDAO.buscarPorCodigo(codigo);
            if (producto == null) {
                return;
            }

            int stock = producto.getStock();
            int nuevoValor = valorActual;

            if (notches < 0) {
                // Rueda hacia arriba → aumentar
                if (valorActual < stock) {
                    nuevoValor++;
                }
            } else {
                // Rueda hacia abajo → disminuir
                if (valorActual > 1) {
                    nuevoValor--;
                }
            }

            spCantidad.setValue(nuevoValor);
        });

        ////////////////////////////////////////////////////////////////////////
    }

    public void cargarProductosEnTabla() {
        ProductoDAO dao = new ProductoDAO();
        List<Producto> productos = dao.listar();

        DefaultTableModel modelo = (DefaultTableModel) tablaProductos.getModel();
        modelo.setRowCount(0);

        for (Producto p : productos) {
            modelo.addRow(new Object[]{
                p.getCodigo(), // Columna 0
                p.getNombre(), // Columna 1
                p.getPrecioVenta(), // Columna 2
                p.getStock() // Columna 3
            });
        }
    }

    private void inicializarTablaProductos() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{"Código", "Nombre", "Precio", "Stock"}, 0
        );
        tablaProductos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tb_reportes = new javax.swing.JToggleButton();
        tb_entrada = new javax.swing.JToggleButton();
        tb_ventas = new javax.swing.JToggleButton();
        tb_cuenta = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        panelFormulario = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btn_agregar = new javax.swing.JButton();
        spCantidad = new javax.swing.JSpinner();
        jButton11 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        panel = new javax.swing.JPanel();
        btn_SKU = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jButtonSiguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        txtCupon = new javax.swing.JTextField();
        rb_observacion = new javax.swing.JRadioButton();
        rb_cupon = new javax.swing.JRadioButton();
        lbl_total = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        sp_item = new javax.swing.JSpinner();
        btn_actualizarItem = new javax.swing.JButton();
        btn_eliminarItem = new javax.swing.JButton();
        btn_validar = new javax.swing.JButton();
        lbl_descuento = new javax.swing.JLabel();
        lbl_subtotal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        miniTabla = new javax.swing.JTable();
        resultadoTotal = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarCodigo = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(1396, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, -1));

        jPanel2.setBackground(new java.awt.Color(255, 51, 0));

        tb_reportes.setBackground(new java.awt.Color(118, 158, 139));
        tb_reportes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tb_reportes.setText("REPORTES");
        tb_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_reportesActionPerformed(evt);
            }
        });

        tb_entrada.setBackground(new java.awt.Color(118, 158, 139));
        tb_entrada.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tb_entrada.setText("R. ENT / SAL");
        tb_entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_entradaActionPerformed(evt);
            }
        });

        tb_ventas.setBackground(new java.awt.Color(118, 158, 139));
        tb_ventas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tb_ventas.setText("VENTAS");
        tb_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_ventasActionPerformed(evt);
            }
        });

        tb_cuenta.setBackground(new java.awt.Color(118, 158, 139));
        tb_cuenta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tb_cuenta.setText("CUENTA");
        tb_cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_cuentaActionPerformed(evt);
            }
        });

        jButton1.setText("R- PRODUCTOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tb_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tb_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tb_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tb_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(695, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tb_reportes, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(tb_entrada, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(tb_ventas, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(tb_cuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 104, 1410, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_agregar.setBackground(new java.awt.Color(0, 153, 0));
        btn_agregar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar.setText("AGREGAR");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        jPanel8.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, 132, 48));
        jPanel8.add(spCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 120, 48));

        jButton11.setBackground(new java.awt.Color(110, 149, 106));
        jButton11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("REPORTAR PRODUCTO");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 530, 200, 50));

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaProductos);

        jPanel8.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 980, 500));

        panel.setBackground(new java.awt.Color(255, 255, 255));

        btn_SKU.setBackground(new java.awt.Color(110, 149, 106));
        btn_SKU.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_SKU.setForeground(new java.awt.Color(255, 255, 255));
        btn_SKU.setText("ESCANEAR SKU");
        btn_SKU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SKUActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(255, 0, 0));
        btn_cancelar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setText("CANCELAR");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        jButtonSiguiente.setBackground(new java.awt.Color(0, 153, 0));
        jButtonSiguiente.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSiguiente.setText("SIGUIENTE");
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtObservaciones);

        txtCupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuponActionPerformed(evt);
            }
        });

        rb_observacion.setText("Observación");
        rb_observacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_observacionActionPerformed(evt);
            }
        });

        rb_cupon.setText("Cupón:");
        rb_cupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_cuponActionPerformed(evt);
            }
        });

        lbl_total.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_total.setText("TOTAL:");

        btn_actualizarItem.setText("Actualizar");
        btn_actualizarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarItemActionPerformed(evt);
            }
        });

        btn_eliminarItem.setText("Eliminar");
        btn_eliminarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(sp_item, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_actualizarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_eliminarItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_actualizarItem)
                    .addComponent(btn_eliminarItem))
                .addContainerGap())
        );

        btn_validar.setText("VALIDAR CUP");
        btn_validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_validarActionPerformed(evt);
            }
        });

        lbl_descuento.setText("Descuento: S./ 0.00");

        lbl_subtotal.setText("Subtotal: S./ 0.00");

        miniTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cantidad", "P/U", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(miniTabla);
        if (miniTabla.getColumnModel().getColumnCount() > 0) {
            miniTabla.getColumnModel().getColumn(0).setResizable(false);
            miniTabla.getColumnModel().getColumn(0).setPreferredWidth(220);
            miniTabla.getColumnModel().getColumn(1).setResizable(false);
            miniTabla.getColumnModel().getColumn(2).setResizable(false);
            miniTabla.getColumnModel().getColumn(3).setResizable(false);
        }

        resultadoTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        resultadoTotal.setText("S/.  0.00");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(rb_observacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(rb_cupon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCupon, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_validar, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(btn_SKU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(resultadoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_SKU, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(rb_observacion))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_subtotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_cupon)
                    .addComponent(txtCupon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_validar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultadoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("PRODUCTO:");

        txtBuscarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarCodigoActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(110, 149, 106));
        jButton12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("FRECUENTES");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        btn_buscar.setBackground(new java.awt.Color(110, 149, 106));
        btn_buscar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar.setText("BUSCAR");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscarCodigo)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelFormularioLayout = new javax.swing.GroupLayout(panelFormulario);
        panelFormulario.setLayout(panelFormularioLayout);
        panelFormularioLayout.setHorizontalGroup(
            panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(374, Short.MAX_VALUE))
        );
        panelFormularioLayout.setVerticalGroup(
            panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(panelFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 152, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private Producto buscarProductoPorNombre(String nombre) {
        ProductoController pc = new ProductoController();
        List<Producto> productos = pc.cargarProductos();

        for (Producto p : productos) {
            if (p.getNombre() != null && p.getNombre().equalsIgnoreCase(nombre.trim())) {
                return p;
            }
        }
        return null;
    }

    private void agregarAlCarrito(Producto p, int cantidad) {
        DefaultTableModel modeloCarrito = (DefaultTableModel) miniTabla.getModel();
        boolean encontrado = false;

        // Recorremos el carrito para ver si el producto ya existe
        for (int i = 0; i < modeloCarrito.getRowCount(); i++) {
            String nombreProducto = modeloCarrito.getValueAt(i, 0).toString();

            if (nombreProducto.equals(p.getNombre())) {
                // Producto ya existe → sumamos cantidad y recalculamos subtotal
                int cantidadActual = (int) modeloCarrito.getValueAt(i, 1);
                int nuevaCantidad = cantidadActual + cantidad;

                modeloCarrito.setValueAt(nuevaCantidad, i, 1); // actualiza cantidad
                double nuevoSubtotal = p.getPrecioVenta() * nuevaCantidad;
                modeloCarrito.setValueAt(nuevoSubtotal, i, 2); // actualiza subtotal

                encontrado = true;
                break;
            }
        }

        // Si no existe → se agrega como nuevo
        if (!encontrado) {
            double subtotal = p.getPrecioVenta() * cantidad;
            Object[] fila = {
                p.getNombre(),
                cantidad,
                subtotal
            };
            modeloCarrito.addRow(fila);
        }

        calcularTotalVenta(); // recalcula el total
    }
    // Limpia el carrito — llamado desde la boleta después de confirmar venta

    public void vaciarCarrito() {
        DefaultTableModel modeloCarrito = (DefaultTableModel) miniTabla.getModel();
        modeloCarrito.setRowCount(0);
        spCantidad.setValue(1);

        lbl_subtotal.setText("Subtotal: S/ 0.00");
        lbl_descuento.setText("Descuento: S/ 0.00");
        resultadoTotal.setText("S/ 0.00");
        txtObservaciones.setText("");
        txtCupon.setText("");
    }

// 🚀 Recalcula subtotal, descuento y total
        public void actualizarTotal() {
        DefaultTableModel modeloCarrito = (DefaultTableModel) miniTabla.getModel();
        double subtotal = 0.0;

        for (int i = 0; i < modeloCarrito.getRowCount(); i++) {
            Object valorSubtotal = modeloCarrito.getValueAt(i, 3); // Columna 3 = Subtotal
            if (valorSubtotal != null) {
                try {
                    subtotal += Double.parseDouble(valorSubtotal.toString());
                } catch (NumberFormatException e) {
                    System.err.println("⚠ Error en fila " + i + ": " + valorSubtotal);
                }
            }
        }

        double descuento = 0.0; // de momento fijo
        double total = subtotal - descuento;

        // Actualiza los labels
        lbl_subtotal.setText("Subtotal: S/ " + String.format("%.2f", subtotal));
        lbl_descuento.setText("Descuento: S/ " + String.format("%.2f", descuento));
        resultadoTotal.setText("S/ " + String.format("%.2f", total));
    }

    private void calcularTotalVenta() {
        DefaultTableModel modeloCarrito = (DefaultTableModel) miniTabla.getModel();
        double total = 0;

        for (int i = 0; i < modeloCarrito.getRowCount(); i++) {
            double precio = Double.parseDouble(modeloCarrito.getValueAt(i, 2).toString());
            int cantidad = Integer.parseInt(modeloCarrito.getValueAt(i, 3).toString());

            total += precio * cantidad;
        }

        resultadoTotal.setText("S/ " + total);
    }

    private double calcularSubtotalCarrito() {
        double subtotalGeneral = 0.0;
        DefaultTableModel carrito = (DefaultTableModel) miniTabla.getModel();

        for (int i = 0; i < carrito.getRowCount(); i++) {
            double subtotal = Double.parseDouble(carrito.getValueAt(i, 3).toString()); // ✅ columna subtotal
            subtotalGeneral += subtotal;
        }
        return subtotalGeneral;
    }

    private void tb_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_reportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_reportesActionPerformed

    private void tb_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_entradaActionPerformed
        jFrame_Asistncias jFrame_Asistncias1;
        jFrame_Asistncias1 = new jFrame_Asistncias();
        jFrame_Asistncias1.setVisible(true);
    }//GEN-LAST:event_tb_entradaActionPerformed

    private void tb_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_ventasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_ventasActionPerformed

    private void tb_cuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_cuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_cuentaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jFrame_añadirProducto jFrame_añadirProducto1 = new jFrame_añadirProducto();
        jFrame_añadirProducto1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        int filaSeleccionada = tablaProductos.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un producto primero.");
            return;
        }

        DefaultTableModel modeloProductos = (DefaultTableModel) tablaProductos.getModel();
        DefaultTableModel modeloCarrito = (DefaultTableModel) miniTabla.getModel();

        String codigo = tablaProductos.getValueAt(filaSeleccionada, 0).toString().trim();
        System.out.println("✅ Código seleccionado: " + codigo);

        // 🔹 Usar DAO para obtener el objeto producto
        ProductoDAO productoDAO = new ProductoDAO();
        Producto producto = productoDAO.buscarPorCodigo(codigo);

        if (producto == null) {
            JOptionPane.showMessageDialog(this, "❌ No se encontró el producto en el DAO");
            return;
        }

        // 🔹 Obtener la cantidad del spinner
        int cantidad = (int) spCantidad.getValue();

        // 🔹 Validar stock
        if (cantidad > producto.getStock()) {
            JOptionPane.showMessageDialog(this, "⚠ Stock insuficiente. Solo hay " + producto.getStock() + " unidades.");
            return;
        }

        // 🔹 Calcular subtotal
        double precioUnitario = producto.getPrecioVenta();
        double subtotal = precioUnitario * cantidad;

        // 🚀 Agregar al carrito en el orden pedido
        modeloCarrito.addRow(new Object[]{
            producto.getNombre(), // Columna 0: Nombre
            cantidad, // Columna 1: Cantidad
            precioUnitario, // Columna 2: P/U
            subtotal // Columna 3: Subtotal
        });

        // 🔹 Recalcular totales
        actualizarTotal();
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        int fila = tablaProductos.getSelectedRow();
        if (fila != -1) {
            String nombre = tablaProductos.getValueAt(fila, 0).toString();
            String codigo = tablaProductos.getValueAt(fila, 3).toString();

            String reporte = JOptionPane.showInputDialog(this, "Ingrese el reporte del producto " + nombre + ":");

            if (reporte != null && !reporte.trim().isEmpty()) {
                try (BufferedWriter bw = new BufferedWriter(new FileWriter("reportes.txt", true))) {
                    bw.write("Producto: " + nombre + " (" + codigo + ") - Reporte: " + reporte);
                    bw.newLine();
                    JOptionPane.showMessageDialog(this, "Reporte guardado correctamente.");
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, "Error al guardar el reporte.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un producto para reportar.");
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btn_SKUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SKUActionPerformed
        // Cambiar texto y bloquear botón mientras simula escaneo
        btn_SKU.setText("Escaneando...");
        btn_SKU.setEnabled(false);

        // Crear Timer (ejecuta la acción tras 2000 ms)
        Timer t = new Timer(2000, e -> {
            ProductoController pc = new ProductoController();
            List<Producto> productos = pc.cargarProductos();

            if (productos.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay productos cargados.");
            } else {
                Random rand = new Random();
                Producto p = productos.get(rand.nextInt(productos.size()));

                int cantidad = 1; // cantidad por defecto al escanear
                if (p.getStock() > 0) {
                    DefaultTableModel modeloCarrito = (DefaultTableModel) miniTabla.getModel();

                    // Agregar en formato correcto: Código, Nombre, Precio, Cantidad
                    modeloCarrito.addRow(new Object[]{
                        p.getCodigo(),
                        p.getNombre(),
                        p.getPrecioVenta(),
                        cantidad
                    });

                    // recalcular total
                    actualizarTotal();

                    JOptionPane.showMessageDialog(this, "✅ Producto escaneado: " + p.getNombre());
                } else {
                    JOptionPane.showMessageDialog(this, "❌ El producto " + p.getNombre() + " no tiene stock.");
                }
            }

            // Restaurar el botón
            btn_SKU.setText("ESCANEAR SKU");
            btn_SKU.setEnabled(true);
        });

        t.setRepeats(false);
        t.start();
    }//GEN-LAST:event_btn_SKUActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        DefaultTableModel modeloCarrito = (DefaultTableModel) miniTabla.getModel();
        modeloCarrito.setRowCount(0); // vacía el carrito
        spCantidad.setValue(1);
        sp_item.setValue(1);

        lbl_subtotal.setText("Subtotal: S/ 0.00");
        lbl_descuento.setText("Descuento: S/ 0.00");
        resultadoTotal.setText("S/ 0.00");

        txtObservaciones.setText("");
        txtCupon.setText("");
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        DefaultTableModel carrito = (DefaultTableModel) miniTabla.getModel();
        DefaultTableModel carritoClonado = new DefaultTableModel(new Object[]{"Producto", "Cantidad", "Subtotal"}, 0);

        for (int i = 0; i < carrito.getRowCount(); i++) {
            Object[] fila = {
                carrito.getValueAt(i, 0),
                carrito.getValueAt(i, 1),
                carrito.getValueAt(i, 2)
            };
            carritoClonado.addRow(fila);
        }

        // 👇 Aquí recogemos lo que ya tienes en tus labels del MenuPrincipal
        String subtotal = lbl_subtotal.getText().replace("Subtotal: ", "");
        String descuento = lbl_descuento.getText().replace("Descuento: ", "");
        String total = lbl_total.getText().replace("Total: ", "");

        // 👇 Usamos el nuevo constructor de la boleta
        jFrame_GenerarBoleta ventanaBoleta;
        ventanaBoleta = new jFrame_GenerarBoleta(
                this,
                carritoClonado,
                subtotal,
                descuento,
                total
        );

        ventanaBoleta.setLocationRelativeTo(this);
        ventanaBoleta.setAlwaysOnTop(true);
        ventanaBoleta.setVisible(true);
        ventanaBoleta.toFront();
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void rb_observacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_observacionActionPerformed
        txtObservaciones.setEnabled(rb_observacion.isSelected());
    }//GEN-LAST:event_rb_observacionActionPerformed

    private void rb_cuponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_cuponActionPerformed
        txtCupon.setEnabled(rb_cupon.isSelected());
    }//GEN-LAST:event_rb_cuponActionPerformed

    private void btn_actualizarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarItemActionPerformed
        int fila = miniTabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto para actualizar.");
            return;
        }

        int nuevaCantidad = (int) sp_item.getValue();
        if (nuevaCantidad <= 0) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a 0.");
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) miniTabla.getModel();

// ✅ Recuperar el código oculto
        String codigo = modelo.getValueAt(fila, 0).toString();

        ProductoDAO productoDAO = new ProductoDAO();
        Producto producto = productoDAO.buscarPorCodigo(codigo);

        if (producto == null) {
            JOptionPane.showMessageDialog(this, "No se encontró el producto en la base de datos.");
            return;
        }

// Validar stock
        if (nuevaCantidad > producto.getStock()) {
            JOptionPane.showMessageDialog(this, "Stock insuficiente. Solo hay " + producto.getStock() + " unidades.");
            return;
        }

// ✅ Actualizar cantidad y subtotal en la tabla
        modelo.setValueAt(nuevaCantidad, fila, 2); // cantidad
        modelo.setValueAt(producto.getPrecioVenta(), fila, 3); // P/U
        modelo.setValueAt(producto.getPrecioVenta() * nuevaCantidad, fila, 4); // subtotal

        actualizarTotal();

    }//GEN-LAST:event_btn_actualizarItemActionPerformed

    private void btn_eliminarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarItemActionPerformed
        int fila = miniTabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto para eliminar.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar este producto?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            DefaultTableModel modelo = (DefaultTableModel) miniTabla.getModel();
            modelo.removeRow(fila);
            actualizarTotal(); // recalcula el total después de eliminar
        }
    }//GEN-LAST:event_btn_eliminarItemActionPerformed

    private void btn_validarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_validarActionPerformed
        String cupon = txtCupon.getText().trim();

        if (cupon.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un cupón primero.");
            return;
        }

        PromocionController promoCtrl = new PromocionController();
        double subtotal = calcularSubtotalCarrito();

        double totalConCupon = promoCtrl.aplicarCupon(cupon, subtotal);

        if (totalConCupon < subtotal) {
            JOptionPane.showMessageDialog(this, "Cupón válido: 10% de descuento aplicado.");
            lbl_descuento.setText("Cupón aplicado: 10%");
            lbl_total.setText(String.format("S/ %.2f", totalConCupon));
        } else {
            JOptionPane.showMessageDialog(this, "Cupón inválido o caducado.");
            lbl_descuento.setText("Sin descuento");
            lbl_total.setText(String.format("S/ %.2f", subtotal));
        }
    }//GEN-LAST:event_btn_validarActionPerformed

    private void txtBuscarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarCodigoActionPerformed

    }//GEN-LAST:event_txtBuscarCodigoActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        ProductoController pc = new ProductoController();
        List<Producto> productos = pc.cargarProductos();

        // Ordenar por vendidos (descendente)
        productos.sort((p1, p2) -> Integer.compare(p2.getVendidos(), p1.getVendidos()));

        // Mostrar en tablaProductos
        DefaultTableModel modelo = (DefaultTableModel) tablaProductos.getModel();
        modelo.setRowCount(0);

        for (Producto p : productos) {
            modelo.addRow(new Object[]{p.getNombre(), p.getPrecioVenta(), p.getStock(), p.getVendidos()});
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        String textoBusqueda = txtBuscarCodigo.getText().trim();
        if (textoBusqueda.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un código o nombre para buscar.");
            return;
        }

        ProductoController pc = new ProductoController();
        List<Producto> productos = pc.cargarProductos();

        DefaultTableModel modelo = (DefaultTableModel) tablaProductos.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        boolean encontrado = false;
        for (Producto p : productos) {
            if (p.getCodigo().equalsIgnoreCase(textoBusqueda)
                    || p.getNombre().equalsIgnoreCase(textoBusqueda)) {
                modelo.addRow(new Object[]{p.getNombre(), p.getPrecioVenta(), p.getStock(), p.getCodigo(), p.getVendidos()});
                encontrado = true;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "Producto no encontrado.");
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void txtCuponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuponActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SKU;
    private javax.swing.JButton btn_actualizarItem;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_eliminarItem;
    private javax.swing.JButton btn_validar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_descuento;
    private javax.swing.JLabel lbl_subtotal;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTable miniTabla;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelFormulario;
    private javax.swing.JRadioButton rb_cupon;
    private javax.swing.JRadioButton rb_observacion;
    private javax.swing.JLabel resultadoTotal;
    private javax.swing.JSpinner spCantidad;
    private javax.swing.JSpinner sp_item;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JToggleButton tb_cuenta;
    private javax.swing.JToggleButton tb_entrada;
    private javax.swing.JToggleButton tb_reportes;
    private javax.swing.JToggleButton tb_ventas;
    private javax.swing.JTextField txtBuscarCodigo;
    private javax.swing.JTextField txtCupon;
    private javax.swing.JTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
